version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - mongo_data:/data/db
    networks:
      - web
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://admin:secret123@mongodb:27017/?authSource=admin
      DB_NAME: mydb
      APP_PORT: 8081
    expose:
      - "8081"
    networks:
      - web

volumes:
  mongo_data:

networks:
  web:
    external: true